version: '3.8'

services:
  user.api:
    image: user-api
    container_name: user-api
    build:
      context: .
      dockerfile: user.api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - AUTH_ISSUER=${AUTH_ISSUER}
      - AUTH_AUDIENCE=${AUTH_AUDIENCE}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_VIRTUAL_HOST=${RABBITMQ_VIRTUAL_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SERVICE_CALL_RETRY_COUNT=${SERVICE_CALL_RETRY_COUNT}
      - OPENSEARCH_NODE_URIS=${OPENSEARCH_NODE_URIS}
      - OPENSEARCH_USER_INDEX_NAME=${OPENSEARCH_USER_INDEX_NAME}
    ports:
      - 5190:80
      - 7076:443
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    restart: always

networks:
  default:
    external: true
    name: local-network